1.Создать вектор (одномерный массив) размера 100, заполненный нулями 

In [1]:
import numpy as np

In [2]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2.Создать вектор размера 100, заполненный единицами

In [3]:
np.ones((100,))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3.Создать вектор размера 100, заполненный числом 3

In [4]:
b = np.ones((100))
b*3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [6]:
b = np.full(100,3)
b

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

4. Как получить документацию о функции numpy.add из командной строки?

In [7]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-7-e4a7e6a4f2e9>, line 1)

In [8]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

5. Поменять 2 строки в матрице

In [15]:
A = np.arange(9).reshape((3,3))
A[[0, 2]] = A[[2, 0]]
A

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

6. Создать вектор со значениями от 10 до 100

In [12]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

7. Развернуть вектор (первый становится последним)

In [18]:
B = np.arange((10))
B = B[::-1]
B

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [19]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [24]:
a = np.array([1, 2, 3, 4, 5])
i = 3
ai = np.zeros(len(a) + (len(a)-1)*(i))
ai[::i+1] = a
ai

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

10. Создать 3x3 единичную матрицу

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11. Создать массив 3x3x3 со случайными значениями

In [26]:
np.random.rand(3, 3, 3)

array([[[0.90208418, 0.48921271, 0.55141652],
        [0.73265012, 0.89998361, 0.55193345],
        [0.08479103, 0.73610533, 0.53458724]],

       [[0.97103338, 0.00961469, 0.04853726],
        [0.96918238, 0.68334592, 0.81741437],
        [0.45052267, 0.91664469, 0.85690166]],

       [[0.88283047, 0.47749397, 0.51442417],
        [0.93295888, 0.06042699, 0.16701425],
        [0.00750758, 0.26332942, 0.42536125]]])

12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [32]:
a = np.random.rand(10, 10)
b = a.min()
c = a.max()
b, c

(0.01745811630594718, 0.9924760732168095)

13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [35]:
A = np.random.rand(30)
B = A.mean()
B

0.5090314491217619

14. Создать матрицу с 0 внутри, и 1 на границах

In [39]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [44]:
A = np.diag(np.array([1, 2, 2, 4]), k=-1)
A

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 4, 0]])

17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [47]:
A = np.ones((8,8), dtype=int)
A[1::2, ::2] = 0
A[::2, 1::2] = 0
A

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [49]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [54]:
a = [0,1]
b = np.tile(a, (8, 4))
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

20. Перемножить матрицы 5x3 и 3x2

In [64]:
A = np.arange(15).reshape((5, 3))
B = np.arange(6).reshape((3, 2))
A.dot(B)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [66]:
a = np.arange(15)
a[(a>3) & (a<=8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [71]:
a = np.arange(5)
np.tile(a, (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

24. Есть генератор, сделать с его помощью массив

In [82]:
def generate():
    for x in range(10):
            yield x
        
a = np.fromiter(generate(), dtype='float', count=-1)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [86]:
A = np.linspace(0,1,12)[1:-1]
A

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

26. Отсортировать вектор

In [89]:
A = np.array([4,7,2,8,1,0,2,7,9])
A.sort()
A

array([0, 1, 2, 2, 4, 7, 7, 8, 9])

27. Проверить, одинаковы ли 2 numpy массива

In [91]:
A = np.array([4,7,2,8,1,0,2,7,9])
B = np.array([4,7,2,8,1,0,2,7,9])
np.allclose(A,B)

True

28. Сделать массив неизменяемым

In [93]:
A = np.array([4,7,2,8,1,0,2,7,9])
A.flags.writeable = False
A[0] = 1

ValueError: assignment destination is read-only

29. Найти n наибольших значений в массиве

In [97]:
A = np.arange(500)
n = 5
A[np.argpartition(-A,n)[:n]]

array([498, 497, 499, 496, 495])

30. Заменить максимальный элемент на ноль

In [100]:
A = np.array([4,7,2,8,1,0,2,7,9])
A[A.argmax()] = 0
A

array([4, 7, 2, 8, 1, 0, 2, 7, 0])

31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [102]:
A = np.zeros((10,10), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
A

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [103]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
np.linalg.det(C)

3638.1636371179666

33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [109]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


34. Напечатать все значения в массиве

In [119]:
a = np.zeros((25,25))
np.set_printoptions(threshold = len(a)*len(a))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

35. Найти ближайшее к заданному значению число в заданном массиве

In [122]:
A = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(A-b)).argmin()
print(A[index])

77


36. Преобразовать массив из float в int

In [134]:
A = np.arange(15, dtype=np.int32)
A = A.astype(np.float32, copy = False)
print(A)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


37. Каков эквивалент функции enumerate для numpy массивов?

In [135]:
A = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(A):
    print(index, value)
for index in np.ndindex(A.shape):
    print(index, A[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


38. Случайно расположить p элементов в 2D массив

In [139]:
n = 10
p = 5
a = np.zeros((n, n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

39. Отнять среднее из каждой строки в матрице

In [141]:
A = np.random.rand(5, 5)
B = A - A.mean(axis = 1, keepdims=True) 
A

array([[0.82287603, 0.85021318, 0.08296489, 0.14471122, 0.68693289],
       [0.83834702, 0.50949648, 0.65870234, 0.93693178, 0.13188357],
       [0.54538156, 0.79836676, 0.87801038, 0.50718585, 0.37017711],
       [0.03980521, 0.92337554, 0.96635373, 0.94917389, 0.47025262],
       [0.309652  , 0.89277499, 0.6706079 , 0.598316  , 0.59065553]])

40. Отсортировать матрицу по n-ому столбцу

In [146]:
A = np.random.randint(0,25,(5,5))
n = 4
print(A)
print(A[A[:,n].argsort()])

[[21  7 15 13  7]
 [24  7  6  3  7]
 [ 0 14 21 15 12]
 [13 14  0 13  0]
 [15  1 12 23 13]]
[[13 14  0 13  0]
 [21  7 15 13  7]
 [24  7  6  3  7]
 [ 0 14 21 15 12]
 [15  1 12 23 13]]


41. Определить, есть ли в 2D массиве нулевые столбцы

In [149]:
a = np.zeros((5,5))
(~a.any(axis=0).any())

True

42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [150]:
a = np.ones(5)
b = np.random.randint(0, len(a), 5)
a += np.bincount(b, minlength=len(a))
a

array([1., 2., 2., 2., 3.])

43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [152]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(n))

[4]


44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [151]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
sum

array([[73, 45, 48, 55],
       [46, 40, 46, 59],
       [46, 46, 54, 51]])