In [1]:
import numpy as np

## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$; $AB$ и $BA$ - неопределены (недопустимая операция)
   
   
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$; $AB$ - $2\times3$; $BA$- неопределена
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$; $AB$ - $3\times 3$; $BA$ - $8\times 8$
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. $AB$ - $4\times 4$; $BA$ - $4\times 4$

In [49]:
A = np.array([[1, 2], [2, 3], [3, 4], [4,5]])
B = np.array([[1, 2], [2, 3], [3, 4], [4,5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
Матрица B
[[1 2]
 [2 3]
 [3 4]
 [4 5]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [50]:
A = np.array([[1, 2, 3, 4, 5], [2, 3, 8, 4, 7]])
B = np.array([[1, 2, 7], [2, 3, 8], [3, 4, 9], [4,5, 11], [2, 6, 3]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1 2 3 4 5]
 [2 3 8 4 7]]
Матрица B
[[ 1  2  7]
 [ 2  3  8]
 [ 3  4  9]
 [ 4  5 11]
 [ 2  6  3]]
Матрица AB
[[ 40  70 109]
 [ 62 107 175]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [51]:
A = np.array([[1, 2, 7, 2, 3, 8,7,0], [3, 4, 9, 4,5, 11, 15, 3], [2, 6, 3, 7, 13, 9, 16, 9]])
B = np.array([[1, 2, 7], [2, 3, 8], [3, 4, 9], [4,5, 11], [2, 6, 3], [4,6,8],[2,45,7],[4,7,6]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1  2  7  2  3  8  7  0]
 [ 3  4  9  4  5 11 15  3]
 [ 2  6  3  7 13  9 16  9]]
Матрица B
[[ 1  2  7]
 [ 2  3  8]
 [ 3  4  9]
 [ 4  5 11]
 [ 2  6  3]
 [ 4  6  8]
 [ 2 45  7]
 [ 4  7  6]]
Матрица AB
[[ 86 427 230]
 [150 866 404]
 [181 984 443]]
Матрица BA
[[ 21  52  46  59 104  93 149  69]
 [ 27  64  65  72 125 121 187  81]
 [ 33  76  84  85 146 149 225  93]
 [ 41  94 106 105 180 186 279 114]
 [ 26  46  77  49  75 109 152  45]
 [ 38  80 106  88 146 170 246  90]
 [151 226 440 233 322 574 801 198]
 [ 37  72 109  78 125 163 229  75]]


In [52]:
A = np.array([[1, 2, 7, 2], [3, 4, 9, 4], [2, 6, 3, 7], [13, 9, 16, 9]])
B = np.array([[1, 2, 7, 2], [3, 4, 9, 4], [2, 6, 3, 7], [13, 9, 16, 9]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1  2  7  2]
 [ 3  4  9  4]
 [ 2  6  3  7]
 [13  9 16  9]]
Матрица B
[[ 1  2  7  2]
 [ 3  4  9  4]
 [ 2  6  3  7]
 [13  9 16  9]]
Матрица AB
[[ 47  70  78  77]
 [ 85 112 148 121]
 [117 109 189 112]
 [189 239 364 255]]
Матрица BA
[[ 47  70  78  77]
 [ 85 112 148 121]
 [117 109 189 112]
 [189 239 364 255]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$ 

Решение:

$$A+B = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$$ 

$$A*B = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$

Проверим:

In [53]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [54]:
A = [[1, 7], [3, -6]]
B = [[0, 5], [2 ,-1]]
C = [[2 ,-4],[1, 1]]

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = \n{3*A +(-2)*B + 4*C}\n") 

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 = 
[[1, 7], [3, -6], [1, 7], [3, -6], [1, 7], [3, -6], [2, -4], [1, 1], [2, -4], [1, 1], [2, -4], [1, 1], [2, -4], [1, 1]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Найдем $A^{T}$ :
$A^{T}=\begin{pmatrix}
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}$. Toгда

$AA^{T}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$ 

$A^{T}A = \begin{pmatrix}
45 & 0\\ 
0 & 14\\ 
\end{pmatrix}$.

Проверка:

In [55]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица AA^T\n{np.dot(A, A.T)}')
print(f'Матрица A^TA\n{np.dot(A.T, A)}')

Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^TA
[[45  0]
 [ 0 14]]



__5.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

Решение:

$$detA=sin^2x + cos^2x = 1$$ 

In [56]:
x = 0;
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), -np.sin(x)]])

print(f'DetA = {np.linalg.det(A):.0f}')

DetA = 1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

Решение:

$$detA = 4*5*9 =180$$

In [57]:
A = np.array([[4,2,3],[0,5,1],[0,0,9]])
print(f'DetA = {np.linalg.det(A):.0f}')

DetA = 180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение:

$$detA = 1*5*9+7*2*6+4*8*3 -7*5*3 -4*9*2 -1*8*6 =0$$

In [58]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'DetA = {np.linalg.det(A):.0f}')

DetA = -0


определитель такой матрицы равен 0 т.к если из второй и третьей строки вычесть первую то вторая и третья строки будет линейно зависимыми

__6.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

*Решение*

Если определить матрицы равен 0, то матрица не вырожденная, найдем определитель

Упростим матрицу

$$\begin{pmatrix} 
1 & -7 & -13\\ 
0 & -7 & 3\\
0 & 0 & 0
\end{pmatrix}$$

Т.к строки матрицы лин. зависимые, то определитель равен 0 => матрица невырожденная

Проверим с помощью библиотки numpy

In [65]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель = {np.linalg.det(A):.0f}')

Определитель = 0


__7.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

*Решение*

In [ ]:
Вычтем из 1 строки 2, а из 3 строки вычтем 2 умноденную на 2

 $\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$

In [ ]:
Первая и третья строки одинаковые, отбрасываем 1 строку

 $\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix}$

Таким образом ранг матрицы равен 2

Проверим это:

In [46]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2
